"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@mantine/core/styles.css'
import Link from "next/link";
import { LoadScript } from "@react-google-maps/api";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

/*export const metadata: Metadata = {
  title: "Gather",
  description: "Generated by create next app",
};*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en"> 
      <body>
        
      <LoadScript googleMapsApiKey="AIzaSyCWOL7uDvqlFYUgIgFfEoekjv7jIJuSHxI">
        {children}
      </LoadScript>

      </body>
    </html>
  );
}
